### PR TITLE
Feature: Allow selection of multiple co-authors

### PR DESCRIPTION
**Pull request by x10an14**
Co-authored-by: @thokra <post@d09.no>

### CODE REVIEW

**Comment by x10an14** [comment]
Thus you can use `<TAB>` to select more than _one_ co-author before you press `<ENTER>`! =D

**Comment by maxjacobson** [comment]
Neat! I didn't know about this option. Do you mind also updating the readme to mention that this is possible?

**Comment by x10an14** [comment]
Just letting you know this is not forgotten! Just haven't had the time yet really.

Kinda also wanna add the option of having some local cache to "fill-in" when say starting a new repository with your colleagues.
This plugin pre-supposes that they've committed anything before you can add them as co-authors, even when pair-programming on a single screen =)

I think that ought to be a second PR though - so expect just the doc to come for _this_ PR.

**Comment by maxjacobson** [comment]
Thanks!

**Comment by maxjacobson** [comment]
> Kinda also wanna add the option of having some local cache to "fill-in" when say starting a new repository with your colleagues.

Fun idea btw!

**Pull request merged**
